baseURL: 'https://buetsec.github.io'
languageCode: en-us

title: "BUET Cyber Security Club"
theme: "papermod"

publishDir: "docs"
comments: false
math: false

params:
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: [ "title" ]

    defaultTheme: light
    disableThemeToggle: true
    ShowCodeCopyButtons: true
    profileMode:
        enabled: true
        title: "Welcome to BUET Cyber Security Club" # optional default will be site title
        imageUrl: "images/buetsec_logo.jpg" # optional
        imageTitle: "BUET Cyber Security Club Logo" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: "Visit Us On Facebook"
            url: "https://facebook.com/buetsec" 

    socialIcons: # optional
      - name: "Facebook"
        url: "https://facebook.com/buetsec"
      - name: "GitHub"
        url: "https://github.com/buetsec"
      - name: "Email"
        url: "mailto:buetsec@gmail.com"

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: team
      name: Team
      url: /team/
      weight: 3
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 4
    - identifier: search
      name: Search
      url: /search/
      weight: 5

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary